---
- name: install docker-nginx for all nodes
  hosts: all
  become: yes
  roles:
   - dckr_nodex-nginx

- name: install grafana to one of the nodes
  hosts: grafana
  become: yes
  roles:
   - dckr_nodex-nginx-grafana

- name: install prometheus to one of the nodes
  hosts: prom_alert
  become: yes
  roles:
   - dckr_nodex-nginx-prom-alert