---
- name: alert manager | create directory
  become: yes
  file:
    path: "{{ alert_manager_volume_source }}"
    mode: 0755 
    state: directory 

- name: alert manager | copy alert_manager config file
  become: yes
  template: 
    src: alert_manager.yml.j2
    dest: "{{ alert_manager_volume_source }}/{{ alert_manager_config_file_name }}"
    owner: root
    mode: 0644

- name: alert manager | start alert_manager container
  become: yes
  docker_container:
    name: "{{ alert_manager_container_name }}"
    hostname: "{{ alert_manager_container_name }}"
    image: "{{ alert_manager_container_image }}"
    volumes:
     - "/tmp/alert_manager/alert_manager.yml:/etc/alertmanager/alertmanager.yml"
    published_ports:
      - 9093:9093
    command:
     - '--config.file=/etc/alertmanager/alertmanager.yml'
     - "--web.external-url=http://localhost:9093/alerts/"
    restart_policy: always