---
- name: nginx | create directory
  become: yes
  file:
    path: "{{ nginx_base_directory }}"
    state: directory
    mode: 0755

- name: nginx | copy config file
  become: yes
  template:
    src: nginx.j2
    dest: "{{ nginx_base_directory }}/nginx.conf"
    mode: 0644
  notify: restart-docker-nginx

- name: nginx | start nginx container
  become: yes
  docker_container:
    image: "nginx"
    name: "{{ nginx_container_name }}"
    volumes: '{{ nginx_exposed_volumes }}'
    ports: '{{ nginx_published_ports }}'
    exposed_ports: '{{ nginx_exposed_ports }}'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_options:
      tag: "{{ nginx_container_name }}"